version: '3.8'
services:
  signal_chain_be:
    build: .
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - '3001:3001'
    env_file:
      ./.env
  signal_chain_fe:
    build: ./../gear-closet-frontend/my-app
    volumes:
      - /app/node_modules
      - ./../gear-closet-frontend/my-app:/app
    ports:
      - '3000:3000'